#!/bin/bash
# Assert that a freshly applied BIND configuration still answers correctly.
#
# This runs after every apply, and it exists to catch a specific failure mode
# that a health check alone cannot: a candidate that raises QPS by answering
# *differently* rather than faster. A config that loses authority, starts
# recursing, or stops resolving the test zone must be rolled back even though
# named is up and responding.
#
# Exit 0 if every assertion holds, 1 otherwise. Prints one line per assertion.

set -uo pipefail

CONF=${1:-/usr/local/lib/dns-tuner/conformance.conf}

# Defaults; conformance.conf may override any of these. ns1.<sld> A 10.10.1.2 is
# emitted both by zone_file_defaults/db.workbench.lan and by
# zone_generation/zone_generator.py, so it survives a zone regeneration.
SERVER=127.0.0.1
PROBE_NAME=ns1.workbench.lan
PROBE_TYPE=A
PROBE_EXPECT=10.10.1.2
ABSENT_NAME=definitely-absent-probe.workbench.lan
RECURSE_NAME=www.example.com
DIG_OPTS="+timeout=2 +tries=1"

# Only assert that the live config was written by the tuner when the caller
# knows it should have been -- i.e. straight after an apply. The pristine
# baseline config legitimately carries no generated header, so asserting this
# unconditionally would fail every baseline check.
EXPECT_TUNER_MANAGED=${EXPECT_TUNER_MANAGED:-no}

# shellcheck source=/dev/null
[ -r "$CONF" ] && . "$CONF"

fails=0
check() {
    local label=$1 outcome=$2 detail=${3:-}
    if [ "$outcome" = "pass" ]; then
        printf '  [ ok ] %s\n' "$label"
    else
        printf '  [FAIL] %s%s\n' "$label" "${detail:+ -- $detail}"
        fails=$((fails+1))
    fi
}

# 1. The server answers for the test zone, with the expected data.
answer=$(dig $DIG_OPTS +short "@$SERVER" "$PROBE_NAME" "$PROBE_TYPE" 2>/dev/null | head -1)
if [ -z "$answer" ]; then
    check "answers $PROBE_NAME/$PROBE_TYPE" fail "empty answer"
elif [ -n "$PROBE_EXPECT" ] && [ "$answer" != "$PROBE_EXPECT" ]; then
    check "answers $PROBE_NAME/$PROBE_TYPE" fail "got '$answer', expected '$PROBE_EXPECT'"
else
    check "answers $PROBE_NAME/$PROBE_TYPE = $answer" pass
fi

# 2. NOERROR, and the AA bit is set -- it is still authoritative, not a cache.
full=$(dig $DIG_OPTS "@$SERVER" "$PROBE_NAME" "$PROBE_TYPE" 2>/dev/null)
case "$full" in
    *"status: NOERROR"*) check "rcode NOERROR" pass ;;
    *) check "rcode NOERROR" fail "$(printf '%s' "$full" | grep -o 'status: [A-Z]*' | head -1)" ;;
esac
case "$full" in
    *"flags:"*" aa"*) check "authoritative (aa flag set)" pass ;;
    *) check "authoritative (aa flag set)" fail "aa flag missing" ;;
esac

# 3. A name that is absent from the zone must be NXDOMAIN, not NOERROR or
#    SERVFAIL -- proves the zone actually loaded rather than partially failing.
absent=$(dig $DIG_OPTS "@$SERVER" "$ABSENT_NAME" A 2>/dev/null)
case "$absent" in
    *"status: NXDOMAIN"*) check "NXDOMAIN for an absent name" pass ;;
    *) check "NXDOMAIN for an absent name" fail "$(printf '%s' "$absent" | grep -o 'status: [A-Z]*' | head -1)" ;;
esac

# 4. Recursion must still be refused. This is the assertion that catches a
#    candidate which somehow dropped the `recursion no` invariant.
recurse=$(dig $DIG_OPTS "@$SERVER" "$RECURSE_NAME" A 2>/dev/null)
case "$recurse" in
    *"status: REFUSED"*|*"status: SERVFAIL"*|*"status: NXDOMAIN"*)
        check "recursion refused" pass ;;
    *"status: NOERROR"*)
        # NOERROR with an answer section means it actually resolved -> recursing.
        if printf '%s' "$recurse" | grep -q 'ANSWER: [1-9]'; then
            check "recursion refused" fail "server resolved $RECURSE_NAME -- recursion is ON"
        else
            check "recursion refused" pass
        fi ;;
    *) check "recursion refused" fail "unexpected response" ;;
esac

# 5. After an apply, the live config must be the one the tuner just rendered --
#    a missing header would mean something else overwrote it mid-flight. Skipped
#    for the baseline, which is the pristine repo file by design.
if [ "$EXPECT_TUNER_MANAGED" = "yes" ] && [ -r /etc/bind/named.conf.options ]; then
    if grep -q 'GENERATED BY config_tuner' /etc/bind/named.conf.options; then
        check "named.conf.options is tuner-managed" pass
    else
        check "named.conf.options is tuner-managed" fail "missing generated header"
    fi
fi

if [ "$fails" -gt 0 ]; then
    printf '  conformance FAILED (%d assertion(s))\n' "$fails"
    exit 1
fi
printf '  conformance passed\n'
exit 0
