# Forward zones
# Equivalent to bind/resolver/named.conf.local
# Forward queries for workbench.lan and dns64perf.test to 10.10.1.2.
# "forward only" (forward-first: no) means do not fall back to recursion.

forward-zone:
	name: "workbench.lan"
	forward-addr: 10.10.1.2
	forward-first: no

forward-zone:
	name: "dns64perf.test"
	forward-addr: 10.10.1.2
	forward-first: no
