server:
	username: "root"
	interface: 10.10.1.1
	interface: 127.0.0.1
	access-control: 0.0.0.0/0 allow
	access-control: ::0/0 allow
	auto-trust-anchor-file: "/usr/local/etc/unbound/root.key"
	domain-insecure: "workbench.lan"
	domain-insecure: "dns64perf.test"
	num-threads: 40
	so-reuseport: yes

# Include forward zone definitions.
include: "/usr/local/etc/unbound/forward.conf"