#
# Unbound resolver configuration.
# Equivalent to bind/resolver/named.conf.options + named.conf.local
#
# See unbound.conf(5) man page, version 1.24.2.
#

# The server clause sets the main parameters.
server:
	# specify the interfaces to answer queries from by ip-address.
	# The default is to listen to localhost (127.0.0.1 and ::1).
	# specify every interface[@port] on a new 'interface:' labelled line.
	interface: 10.10.1.1
	interface: 127.0.0.1

	# control which clients are allowed to make (recursive) queries
	# to this server. Specify classless netblocks with /size and action.
	# By default everything is refused, except for localhost.
	# Choose deny (drop message), refuse (polite error reply),
	# allow (recursive ok), allow_setrd (recursive ok, rd bit is forced on),
	# allow_snoop (recursive and nonrecursive ok)
	access-control: 0.0.0.0/0 allow
	access-control: ::0/0 allow

	# File with trusted keys, kept uptodate using RFC5011 probes,
	# initial file like trust-anchor-file, then it stores metadata.
	# Use several entries, one per domain name, to track multiple zones.
	#
	# If you want to perform DNSSEC validation, run unbound-anchor before
	# you start Unbound (i.e. in the system boot scripts).
	# And then enable the auto-trust-anchor-file config item.
	# Please note usage of unbound-anchor root anchor is at your own risk
	# and under the terms of our LICENSE (see that file in the source).
	#auto-trust-anchor-file: "/usr/local/etc/unbound/root.key"

	# Ignore chain of trust. Domain is treated as insecure.
	domain-insecure: "workbench.lan"
	domain-insecure: "dns64perf.test"

# Include forward zone definitions.
include: "/usr/local/etc/unbound/forward.conf"
