network:
  listen:
    - interface: 10.10.1.1@53
    - interface: 127.0.0.1@53
dnssec:
  enable: false
forward:
  - subtree: workbench.lan.
    options:
      authoritative: false
    servers:
      - address:
          - 10.10.1.2@53
  - subtree: dns64perf.test.
    options:
      authoritative: false
    servers:
      - address:
          - 10.10.1.2@53