workers: auto
network:
  listen:
    - interface: 10.10.1.1@53
    - interface: 127.0.0.1@53
forward:
  - subtree:
      - workbench.lan
      - dns64perf.test
    servers:
      - 10.10.1.2
    options:
      authoritative: true
      dnssec: false