server:
	username: "root"
	ip-address: 10.10.1.2
	ip-address: 127.0.0.1
	zonesdir: "/etc/nsd/"
	pidfile: "/var/run/nsd.pid"
	server-count: 40
	reuseport: yes

zone:
	name: "workbench.lan"
	zonefile: "db.workbench.lan"

zone:
	name: "dns64perf.test"
	zonefile: "db.dns64perf.test"