hosts:
  server: 10.10.1.2
  clients:
    - 10.10.1.3
    - 10.10.1.4

server_interface: enp1s0d1
client_interface: enp1s0d1

input_files:
  dnsperf: /local/repository/dnsperf_input
  dnspyre: /local/repository/dnspyre_input

dns_services:
  start_script: /local/repository/start_dns_service.sh
  stop_script: /local/repository/stop_dns_service.sh
  clear_cache_script: /local/repository/clear_cache.sh
  services:
    - ns_bind

tools:
  - kxdpgun

threads: 8
timeout: 1
runtime: 60
pause_between_runs: 5
max_delay_between_bursts: 1000000

max_sustainable_qps:
  initial_qps: 100000
  min_qps_step: 10000
  max_qps: 3000000
  num_trials: 5
  min_passes: 4
  trial_duration: 10
  answer_rate_threshold: 99.0
  min_qps_fidelity_pct: 99.0
  clear_cache: false
  warmup_cache: false
  collectl: false
  collectl_margin: 5
