server:
	username: "root"
	interface: 10.10.1.2
	interface: 127.0.0.1
	access-control: 0.0.0.0/0 allow
	access-control: ::0/0 allow

	# Disable recursion for authoritative-only mode
	do-not-query-localhost: yes
	module-config: "iterator"

auth-zone:
	name: "workbench.lan"
	zonefile: "/usr/local/etc/unbound/db.workbench.lan"

auth-zone:
	name: "dns64perf.test"
	zonefile: "/usr/local/etc/unbound/db.dns64perf.test"
