incoming:
  listen:
    - 10.10.1.1
    - 127.0.0.1
  allow_from:
    - 0.0.0.0/0
    - ::/0
dnssec:
  validation: validate
  negative_trustanchors:
    - name: workbench.lan
    - name: dns64perf.test
  trustanchorfile: /usr/share/dns/root.key
recursor:
  hint_file: /usr/share/dns/root.hints
  include_dir: /etc/powerdns/recursor.d
  forward_zones:
    - zone: workbench.lan
      forwarders:
        - 10.10.1.2
    - zone: dns64perf.test
      forwarders:
        - 10.10.1.2