server:
    rundir: "/run/knot"
    user: knot:knot
    listen: [ 10.10.1.2@53, 127.0.0.1@53 ]

log:
  - target: syslog
    any: info

database:
    storage: "/var/lib/knot"

template:
  - id: default
    storage: "/var/lib/knot"
    file: "%s.zone"

zone:
  - domain: workbench.lan
    file: "/etc/knot/db.workbench.lan"
  - domain: dns64perf.test
    file: "/etc/knot/db.dns64perf.test"
